services:
  cms:
    build:
      context: "./apps/cms"
      dockerfile: Dockerfile
    volumes:
      - "./apps/cms/admin:/usr/share/nginx/html"
    ports:
      - 8080:80
    networks:
      - apps
  web:
    build:
      context: "./apps/website"
      dockerfile: Dockerfile
      target: dev
    volumes:
      - "./apps/website/src:/app/src"
      - "./apps/website/gatsby-browser.js:/app/gatsby-browser.js"
      - "./apps/website/gatsby-config.ts:/app/gatsby-config.ts"
      - "./apps/website/gatsby-node.ts:/app/gatsby-node.ts"
      - "./apps/website/postcss.config.js:/app/postcss.config.js"
      - "./apps/website/tailwind.config.js:/app/tailwind.config.js"
      - "./apps/website/tsconfig.json:/app/tsconfig.json"
    ports:
      - 8081:8000
    networks:
      - apps
  projects-web:
    build:
      context: "./apps/projects"
      dockerfile: Dockerfile
      target: dev
    volumes:
      - "./apps/projects/app:/app/app"
      - "./apps/projects/components:/app/components"
      - "./apps/projects/lib:/app/lib"
      - "./apps/projects/.eslintrc.js:/app/.eslintrc.js"
      - "./apps/projects/components.json:/app/components.json"
      - "./apps/projects/next.config.mjs:/app/next.config.mjs"
      - "./apps/projects/postcss.config.mjs:/app/postcss.config.mjs"
      - "./apps/projects/tailwind.config.ts:/app/tailwind.config.ts"
      - "./apps/projects/tsconfig.json:/app/tsconfig.json"
    ports:
      - 8082:3000
    networks:
      - apps
  projects-api:
    build:
      context: "./apps/projects/api"
      dockerfile: Dockerfile
      target: dev
    volumes:
      - "./apps/projects/api/src:/app/src"
      - "./apps/projects/api/.env:/app/.env"
      - "./apps/projects/api/tsconfig.json:/app/tsconfig.json"
    ports:
      - 8083:4000
    networks:
      - apps
  proxy:
    build:
      context: "./apps/proxy"
      dockerfile: Dockerfile
    networks:
      - apps
    ports:
      - 80:80

networks:
  apps: