name: Build and Push Docker Image

# Run this workflow whenever there's a push to the main branch
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx (optional, if you're building multi-platform images)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub (or GitHub Container Registry)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # Set in repository secrets
          password: ${{ secrets.DOCKER_TOKEN }} # Set in repository secrets

      # Step 4: Build the Docker image
      - name: Build Docker image
        run: |
          cd apps/projects
          docker build -t jawadc/cimpl-projects-mfe:${{ github.sha }} .

      # Step 5: Push the Docker image
      - name: Push Docker image
        run: |
          docker push jawadc/cimpl-projects-mfe:${{ github.sha }}

      # Optional: Set up latest tag for the image
      - name: Tag image as latest
        run: |
          docker tag jawadc/cimpl-projects-mfe:${{ github.sha }} jawadc/cimpl-projects-mfe:latest
          docker push jawadc/cimpl-projects-mfe:latest
